name: Validation and Bias Check Pipeline

on:
  push:
    paths:
      - 'Model Pipeline/Model Evaluation/evaluation.py'
      - 'Model Pipeline/Model Evaluation/bias_evaluation.py'
      - 'Model Pipeline/Model Evaluation/question.xlsx'
      - 'Model Pipeline/Model Evaluation/bias_question.xlsx'

  workflow_dispatch:

jobs:
  validate_and_check_bias:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Model Pipeline/Model Evaluation/requirements.txt"

      - name: Run validation script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python "Model Pipeline/Model Evaluation/evaluation.py"

      - name: Run bias check script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python "Model Pipeline/Model Evaluation/bias_evaluation.py"

      - name: Save results artifact
        uses: actions/upload-artifact@v4
        with:
          name: validation-and-bias-results
          path: "Model Pipeline/Model Evaluation/"